const InvoiceActionTypes = {
  ADD_INVOICE_SUCCESS: "ADD_INVOICE_SUCCESS",
  ADD_INVOICE_FAILURE: "ADD_INVOICE_FAILURE",
  ADD_INVOICE_START: "ADD_INVOICE_START",
  EDIT_INVOICE_SUCCESS: "EDIT_INVOICE_SUCCESS",
  EDIT_INVOICE_FAILURE: "EDIT_INVOICE_FAILURE",
  EDIT_INVOICE_START: "EDIT_INVOICE_START",
  FETCH_USER_INVOICES_SUCCESS: "FETCH_USER_INVOICES_SUCCESS",
  FETCH_USER_INVOICES_FAILURE: "FETCH_USER_INVOICES_FAILURE",
  FETCH_USER_INVOICES_START: "FETCH_USER_INVOICES_START",
  FETCH_INVOICES_SUCCESS: "FETCH_INVOICES_SUCCESS",
  FETCH_INVOICES_FAILURE: "FETCH_INVOICES_FAILURE",
  FETCH_INVOICES_START: "FETCH_INVOICES_START",
};

export default InvoiceActionTypes;
