const AuthorityActionTypes = {
  ADD_AUTHORITY_SUCCESS: "ADD_AUTHORITY_SUCCESS",
  ADD_AUTHORITY_FAILURE: "ADD_AUTHORITY_FAILURE",
  ADD_AUTHORITY_START: "ADD_AUTHORITY_START",
  EDIT_AUTHORITY_SUCCESS: "EDIT_AUTHORITY_SUCCESS",
  EDIT_AUTHORITY_FAILURE: "EDIT_AUTHORITY_FAILURE",
  EDIT_AUTHORITY_START: "EDIT_AUTHORITY_START",
  DELETE_AUTHORITY_SUCCESS: "DELETE_AUTHORITY_SUCCESS",
  DELETE_AUTHORITY_FAILURE: "DELETE_AUTHORITY_FAILURE",
  DELETE_AUTHORITY_START: "DELETE_AUTHORITY_START",
  FETCH_AUTHORITIES_SUCCESS: "FETCH_AUTHORITIES_SUCCESS",
  FETCH_AUTHORITIES_FAILURE: "FETCH_AUTHORITIES_FAILURE",
  FETCH_AUTHORITIES_START: "FETCH_AUTHORITIES_START",
};

export default AuthorityActionTypes;
