const NoteActionTypes = {
  ADD_NOTE_SUCCESS: "ADD_NOTE_SUCCESS",
  ADD_NOTE_FAILURE: "ADD_NOTE_FAILURE",
  ADD_NOTE_START: "ADD_NOTE_START",
  EDIT_NOTE_SUCCESS: "EDIT_NOTE_SUCCESS",
  EDIT_NOTE_FAILURE: "EDIT_NOTE_FAILURE",
  EDIT_NOTE_START: "EDIT_NOTE_START",
  FETCH_NOTES_SUCCESS: "FETCH_NOTES_SUCCESS",
  FETCH_NOTES_FAILURE: "FETCH_NOTES_FAILURE",
  FETCH_NOTES_START: "FETCH_NOTES_START",
};

export default NoteActionTypes;
