const UserActionTypes = {
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_IN_START: "SIGN_IN_START",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  CHECK_USER_SESSION_DONE: "CHECK_USER_SESSION_DONE",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  FETCH_EMPLOYEES_START: "FETCH_EMPLOYEES_START",
  FETCH_EMPLOYEES_SUCCESS: "FETCH_EMPLOYEES_SUCCESS",
  FETCH_EMPLOYEES_FAILURE: "FETCH_EMPLOYEES_FAILURE",
  ADD_EMPLOYEE_SUCCESS: "ADD_EMPLOYEE_SUCCESS",
  TEST_HEADER: "TEST_HEADER",
};

export default UserActionTypes;
