const ProductActionTypes = {
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
  ADD_PRODUCT_START: "ADD_PRODUCT_START",
  EDIT_PRODUCT_SUCCESS: "EDIT_PRODUCT_SUCCESS",
  EDIT_PRODUCT_FAILURE: "EDIT_PRODUCT_FAILURE",
  EDIT_PRODUCT_START: "EDIT_PRODUCT_START",
  RATE_PRODUCT_SUCCESS: "RATE_PRODUCT_SUCCESS",
  RATE_PRODUCT_FAILURE: "RATE_PRODUCT_FAILURE",
  RATE_PRODUCT_START: "RATE_PRODUCT_START",
  DEL_PRODUCT_SUCCESS: "DEL_PRODUCT_SUCCESS",
  DEL_PRODUCT_FAILURE: "DEL_PRODUCT_FAILURE",
  DEL_PRODUCT_START: "DEL_PRODUCT_START",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
};

export default ProductActionTypes;
