const CategoryActionTypes = {
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
  ADD_CATEGORY_START: "ADD_CATEGORY_START",
  EDIT_CATEGORY_SUCCESS: "EDIT_CATEGORY_SUCCESS",
  EDIT_CATEGORY_FAILURE: "EDIT_CATEGORY_FAILURE",
  EDIT_CATEGORY_START: "EDIT_CATEGORY_START",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_FAILURE",
  DELETE_CATEGORY_START: "DELETE_CATEGORY_START",
  ADD_SUBCATEGORY_SUCCESS: "ADD_SUBCATEGORY_SUCCESS",
  ADD_SUBCATEGORY_FAILURE: "ADD_SUBCATEGORY_FAILURE",
  ADD_SUBCATEGORY_START: "ADD_SUBCATEGORY_START",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",
  FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
};

export default CategoryActionTypes;
