const MailActionTypes = {
  ADD_MAIL_SUCCESS: "ADD_MAIL_SUCCESS",
  ADD_MAIL_FAILURE: "ADD_MAIL_FAILURE",
  ADD_MAIL_START: "ADD_MAIL_START",
  REP_MAIL_SUCCESS: "REP_MAIL_SUCCESS",
  REP_MAIL_FAILURE: "REP_MAIL_FAILURE",
  REP_MAIL_START: "REP_MAIL_START",
  FETCH_USER_MAILS_SUCCESS: "FETCH_USER_MAILS_SUCCESS",
  FETCH_USER_MAILS_FAILURE: "FETCH_USER_MAILS_FAILURE",
  FETCH_USER_MAILS_START: "FETCH_USER_MAILS_START",
  FETCH_MAILS_SUCCESS: "FETCH_MAILS_SUCCESS",
  FETCH_MAILS_FAILURE: "FETCH_MAILS_FAILURE",
  FETCH_MAILS_START: "FETCH_MAILS_START",
};

export default MailActionTypes;
