const MailActionTypes = {
  ADD_MAIL_SUCCESS: "ADD_MAIL_SUCCESS",
  ADD_MAIL_FAILURE: "ADD_MAIL_FAILURE",
  ADD_MAIL_START: "ADD_MAIL_START",
  FETCH_MAILS_SUCCESS: "FETCH_MAILS_SUCCESS",
  FETCH_MAILS_FAILURE: "FETCH_MAILS_FAILURE",
  FETCH_MAILS_START: "FETCH_MAILS_START",
};

export default MailActionTypes;
